# NOTE: This file is auto generated by OpenAPI Generator 7.5.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule YNAB.Api.Accounts do
  @moduledoc """
  API calls for all endpoints tagged `Accounts`.
  """

  alias YNAB.Connection
  import YNAB.RequestBuilder

  @doc """
  Create a new account
  Creates a new account

  ### Parameters

  - `connection` (YNAB.Connection): Connection to server
  - `budget_id` (String.t): The id of the budget (\"last-used\" can be used to specify the last used budget and \"default\" can be used if default budget selection is enabled (see: https://api.ynab.com/#oauth-default-budget)
  - `data` (PostAccountWrapper): The account to create.
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, YNAB.Model.AccountResponse.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec create_account(
          Tesla.Env.client(),
          String.t(),
          YNAB.Model.PostAccountWrapper.t(),
          keyword()
        ) ::
          {:ok, YNAB.Model.ErrorResponse.t()}
          | {:ok, YNAB.Model.AccountResponse.t()}
          | {:error, Tesla.Env.t()}
  def create_account(connection, budget_id, data, _opts \\ []) do
    request =
      %{}
      |> method(:post)
      |> url("/budgets/#{budget_id}/accounts")
      |> add_param(:body, :body, data)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {201, YNAB.Model.AccountResponse},
      {400, YNAB.Model.ErrorResponse}
    ])
  end

  @doc """
  Single account
  Returns a single account

  ### Parameters

  - `connection` (YNAB.Connection): Connection to server
  - `budget_id` (String.t): The id of the budget. \"last-used\" can be used to specify the last used budget and \"default\" can be used if default budget selection is enabled (see: https://api.ynab.com/#oauth-default-budget).
  - `account_id` (String.t): The id of the account
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, YNAB.Model.AccountResponse.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec get_account_by_id(Tesla.Env.client(), String.t(), String.t(), keyword()) ::
          {:ok, YNAB.Model.ErrorResponse.t()}
          | {:ok, YNAB.Model.AccountResponse.t()}
          | {:error, Tesla.Env.t()}
  def get_account_by_id(connection, budget_id, account_id, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/budgets/#{budget_id}/accounts/#{account_id}")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, YNAB.Model.AccountResponse},
      {404, YNAB.Model.ErrorResponse},
      {:default, YNAB.Model.ErrorResponse}
    ])
  end

  @doc """
  Account list
  Returns all accounts

  ### Parameters

  - `connection` (YNAB.Connection): Connection to server
  - `budget_id` (String.t): The id of the budget. \"last-used\" can be used to specify the last used budget and \"default\" can be used if default budget selection is enabled (see: https://api.ynab.com/#oauth-default-budget).
  - `opts` (keyword): Optional parameters
    - `:last_knowledge_of_server` (integer()): The starting server knowledge.  If provided, only entities that have changed since `last_knowledge_of_server` will be included.

  ### Returns

  - `{:ok, YNAB.Model.AccountsResponse.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec get_accounts(Tesla.Env.client(), String.t(), keyword()) ::
          {:ok, YNAB.Model.ErrorResponse.t()}
          | {:ok, YNAB.Model.AccountsResponse.t()}
          | {:error, Tesla.Env.t()}
  def get_accounts(connection, budget_id, opts \\ []) do
    optional_params = %{
      :last_knowledge_of_server => :query
    }

    request =
      %{}
      |> method(:get)
      |> url("/budgets/#{budget_id}/accounts")
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, YNAB.Model.AccountsResponse},
      {404, YNAB.Model.ErrorResponse},
      {:default, YNAB.Model.ErrorResponse}
    ])
  end
end
