# NOTE: This file is auto generated by OpenAPI Generator 7.5.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule YNAB.Api.Categories do
  @moduledoc """
  API calls for all endpoints tagged `Categories`.
  """

  alias YNAB.Connection
  import YNAB.RequestBuilder

  @doc """
  List categories
  Returns all categories grouped by category group.  Amounts (budgeted, activity, balance, etc.) are specific to the current budget month (UTC).

  ### Parameters

  - `connection` (YNAB.Connection): Connection to server
  - `budget_id` (String.t): The id of the budget. \"last-used\" can be used to specify the last used budget and \"default\" can be used if default budget selection is enabled (see: https://api.ynab.com/#oauth-default-budget).
  - `opts` (keyword): Optional parameters
    - `:last_knowledge_of_server` (integer()): The starting server knowledge.  If provided, only entities that have changed since `last_knowledge_of_server` will be included.

  ### Returns

  - `{:ok, YNAB.Model.CategoriesResponse.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec get_categories(Tesla.Env.client(), String.t(), keyword()) ::
          {:ok, YNAB.Model.CategoriesResponse.t()}
          | {:ok, YNAB.Model.ErrorResponse.t()}
          | {:error, Tesla.Env.t()}
  def get_categories(connection, budget_id, opts \\ []) do
    optional_params = %{
      :last_knowledge_of_server => :query
    }

    request =
      %{}
      |> method(:get)
      |> url("/budgets/#{budget_id}/categories")
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, YNAB.Model.CategoriesResponse},
      {404, YNAB.Model.ErrorResponse},
      {:default, YNAB.Model.ErrorResponse}
    ])
  end

  @doc """
  Single category
  Returns a single category.  Amounts (budgeted, activity, balance, etc.) are specific to the current budget month (UTC).

  ### Parameters

  - `connection` (YNAB.Connection): Connection to server
  - `budget_id` (String.t): The id of the budget. \"last-used\" can be used to specify the last used budget and \"default\" can be used if default budget selection is enabled (see: https://api.ynab.com/#oauth-default-budget).
  - `category_id` (String.t): The id of the category
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, YNAB.Model.CategoryResponse.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec get_category_by_id(Tesla.Env.client(), String.t(), String.t(), keyword()) ::
          {:ok, YNAB.Model.ErrorResponse.t()}
          | {:ok, YNAB.Model.CategoryResponse.t()}
          | {:error, Tesla.Env.t()}
  def get_category_by_id(connection, budget_id, category_id, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/budgets/#{budget_id}/categories/#{category_id}")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, YNAB.Model.CategoryResponse},
      {404, YNAB.Model.ErrorResponse},
      {:default, YNAB.Model.ErrorResponse}
    ])
  end

  @doc """
  Single category for a specific budget month
  Returns a single category for a specific budget month.  Amounts (budgeted, activity, balance, etc.) are specific to the current budget month (UTC).

  ### Parameters

  - `connection` (YNAB.Connection): Connection to server
  - `budget_id` (String.t): The id of the budget. \"last-used\" can be used to specify the last used budget and \"default\" can be used if default budget selection is enabled (see: https://api.ynab.com/#oauth-default-budget).
  - `month` (Date.t): The budget month in ISO format (e.g. 2016-12-01) (\"current\" can also be used to specify the current calendar month (UTC))
  - `category_id` (String.t): The id of the category
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, YNAB.Model.CategoryResponse.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec get_month_category_by_id(Tesla.Env.client(), String.t(), Date.t(), String.t(), keyword()) ::
          {:ok, YNAB.Model.ErrorResponse.t()}
          | {:ok, YNAB.Model.CategoryResponse.t()}
          | {:error, Tesla.Env.t()}
  def get_month_category_by_id(connection, budget_id, month, category_id, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/budgets/#{budget_id}/months/#{month}/categories/#{category_id}")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, YNAB.Model.CategoryResponse},
      {404, YNAB.Model.ErrorResponse},
      {:default, YNAB.Model.ErrorResponse}
    ])
  end

  @doc """
  Update a category
  Update a category

  ### Parameters

  - `connection` (YNAB.Connection): Connection to server
  - `budget_id` (String.t): The id of the budget. \"last-used\" can be used to specify the last used budget and \"default\" can be used if default budget selection is enabled (see: https://api.ynab.com/#oauth-default-budget).
  - `category_id` (String.t): The id of the category
  - `data` (PatchCategoryWrapper): The category to update
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, YNAB.Model.SaveCategoryResponse.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec update_category(
          Tesla.Env.client(),
          String.t(),
          String.t(),
          YNAB.Model.PatchCategoryWrapper.t(),
          keyword()
        ) ::
          {:ok, YNAB.Model.ErrorResponse.t()}
          | {:ok, YNAB.Model.SaveCategoryResponse.t()}
          | {:error, Tesla.Env.t()}
  def update_category(connection, budget_id, category_id, data, _opts \\ []) do
    request =
      %{}
      |> method(:patch)
      |> url("/budgets/#{budget_id}/categories/#{category_id}")
      |> add_param(:body, :body, data)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, YNAB.Model.SaveCategoryResponse},
      {400, YNAB.Model.ErrorResponse}
    ])
  end

  @doc """
  Update a category for a specific month
  Update a category for a specific month.  Only `budgeted` amount can be updated.

  ### Parameters

  - `connection` (YNAB.Connection): Connection to server
  - `budget_id` (String.t): The id of the budget. \"last-used\" can be used to specify the last used budget and \"default\" can be used if default budget selection is enabled (see: https://api.ynab.com/#oauth-default-budget).
  - `month` (Date.t): The budget month in ISO format (e.g. 2016-12-01) (\"current\" can also be used to specify the current calendar month (UTC))
  - `category_id` (String.t): The id of the category
  - `data` (PatchMonthCategoryWrapper): The category to update.  Only `budgeted` amount can be updated and any other fields specified will be ignored.
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, YNAB.Model.SaveCategoryResponse.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec update_month_category(
          Tesla.Env.client(),
          String.t(),
          Date.t(),
          String.t(),
          YNAB.Model.PatchMonthCategoryWrapper.t(),
          keyword()
        ) ::
          {:ok, YNAB.Model.ErrorResponse.t()}
          | {:ok, YNAB.Model.SaveCategoryResponse.t()}
          | {:error, Tesla.Env.t()}
  def update_month_category(connection, budget_id, month, category_id, data, _opts \\ []) do
    request =
      %{}
      |> method(:patch)
      |> url("/budgets/#{budget_id}/months/#{month}/categories/#{category_id}")
      |> add_param(:body, :body, data)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, YNAB.Model.SaveCategoryResponse},
      {400, YNAB.Model.ErrorResponse}
    ])
  end
end
