# NOTE: This file is auto generated by OpenAPI Generator 7.5.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule YNAB.Api.Months do
  @moduledoc """
  API calls for all endpoints tagged `Months`.
  """

  alias YNAB.Connection
  import YNAB.RequestBuilder

  @doc """
  Single budget month
  Returns a single budget month

  ### Parameters

  - `connection` (YNAB.Connection): Connection to server
  - `budget_id` (String.t): The id of the budget. \"last-used\" can be used to specify the last used budget and \"default\" can be used if default budget selection is enabled (see: https://api.ynab.com/#oauth-default-budget).
  - `month` (Date.t): The budget month in ISO format (e.g. 2016-12-01) (\"current\" can also be used to specify the current calendar month (UTC))
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, YNAB.Model.MonthDetailResponse.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec get_budget_month(Tesla.Env.client(), String.t(), Date.t(), keyword()) ::
          {:ok, YNAB.Model.MonthDetailResponse.t()}
          | {:ok, YNAB.Model.ErrorResponse.t()}
          | {:error, Tesla.Env.t()}
  def get_budget_month(connection, budget_id, month, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/budgets/#{budget_id}/months/#{month}")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, YNAB.Model.MonthDetailResponse},
      {404, YNAB.Model.ErrorResponse},
      {:default, YNAB.Model.ErrorResponse}
    ])
  end

  @doc """
  List budget months
  Returns all budget months

  ### Parameters

  - `connection` (YNAB.Connection): Connection to server
  - `budget_id` (String.t): The id of the budget. \"last-used\" can be used to specify the last used budget and \"default\" can be used if default budget selection is enabled (see: https://api.ynab.com/#oauth-default-budget).
  - `opts` (keyword): Optional parameters
    - `:last_knowledge_of_server` (integer()): The starting server knowledge.  If provided, only entities that have changed since `last_knowledge_of_server` will be included.

  ### Returns

  - `{:ok, YNAB.Model.MonthSummariesResponse.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec get_budget_months(Tesla.Env.client(), String.t(), keyword()) ::
          {:ok, YNAB.Model.MonthSummariesResponse.t()}
          | {:ok, YNAB.Model.ErrorResponse.t()}
          | {:error, Tesla.Env.t()}
  def get_budget_months(connection, budget_id, opts \\ []) do
    optional_params = %{
      :last_knowledge_of_server => :query
    }

    request =
      %{}
      |> method(:get)
      |> url("/budgets/#{budget_id}/months")
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, YNAB.Model.MonthSummariesResponse},
      {404, YNAB.Model.ErrorResponse},
      {:default, YNAB.Model.ErrorResponse}
    ])
  end
end
