# NOTE: This file is auto generated by OpenAPI Generator 7.5.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule YNAB.Api.PayeeLocations do
  @moduledoc """
  API calls for all endpoints tagged `PayeeLocations`.
  """

  alias YNAB.Connection
  import YNAB.RequestBuilder

  @doc """
  Single payee location
  Returns a single payee location

  ### Parameters

  - `connection` (YNAB.Connection): Connection to server
  - `budget_id` (String.t): The id of the budget. \"last-used\" can be used to specify the last used budget and \"default\" can be used if default budget selection is enabled (see: https://api.ynab.com/#oauth-default-budget).
  - `payee_location_id` (String.t): id of payee location
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, YNAB.Model.PayeeLocationResponse.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec get_payee_location_by_id(Tesla.Env.client(), String.t(), String.t(), keyword()) ::
          {:ok, YNAB.Model.PayeeLocationResponse.t()}
          | {:ok, YNAB.Model.ErrorResponse.t()}
          | {:error, Tesla.Env.t()}
  def get_payee_location_by_id(connection, budget_id, payee_location_id, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/budgets/#{budget_id}/payee_locations/#{payee_location_id}")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, YNAB.Model.PayeeLocationResponse},
      {404, YNAB.Model.ErrorResponse},
      {:default, YNAB.Model.ErrorResponse}
    ])
  end

  @doc """
  List payee locations
  Returns all payee locations

  ### Parameters

  - `connection` (YNAB.Connection): Connection to server
  - `budget_id` (String.t): The id of the budget. \"last-used\" can be used to specify the last used budget and \"default\" can be used if default budget selection is enabled (see: https://api.ynab.com/#oauth-default-budget).
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, YNAB.Model.PayeeLocationsResponse.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec get_payee_locations(Tesla.Env.client(), String.t(), keyword()) ::
          {:ok, YNAB.Model.PayeeLocationsResponse.t()}
          | {:ok, YNAB.Model.ErrorResponse.t()}
          | {:error, Tesla.Env.t()}
  def get_payee_locations(connection, budget_id, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/budgets/#{budget_id}/payee_locations")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, YNAB.Model.PayeeLocationsResponse},
      {404, YNAB.Model.ErrorResponse},
      {:default, YNAB.Model.ErrorResponse}
    ])
  end

  @doc """
  List locations for a payee
  Returns all payee locations for a specified payee

  ### Parameters

  - `connection` (YNAB.Connection): Connection to server
  - `budget_id` (String.t): The id of the budget. \"last-used\" can be used to specify the last used budget and \"default\" can be used if default budget selection is enabled (see: https://api.ynab.com/#oauth-default-budget).
  - `payee_id` (String.t): id of payee
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, YNAB.Model.PayeeLocationsResponse.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec get_payee_locations_by_payee(Tesla.Env.client(), String.t(), String.t(), keyword()) ::
          {:ok, YNAB.Model.PayeeLocationsResponse.t()}
          | {:ok, YNAB.Model.ErrorResponse.t()}
          | {:error, Tesla.Env.t()}
  def get_payee_locations_by_payee(connection, budget_id, payee_id, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/budgets/#{budget_id}/payees/#{payee_id}/payee_locations")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, YNAB.Model.PayeeLocationsResponse},
      {404, YNAB.Model.ErrorResponse},
      {:default, YNAB.Model.ErrorResponse}
    ])
  end
end
