# NOTE: This file is auto generated by OpenAPI Generator 7.5.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule YNAB.Api.ScheduledTransactions do
  @moduledoc """
  API calls for all endpoints tagged `ScheduledTransactions`.
  """

  alias YNAB.Connection
  import YNAB.RequestBuilder

  @doc """
  Single scheduled transaction
  Returns a single scheduled transaction

  ### Parameters

  - `connection` (YNAB.Connection): Connection to server
  - `budget_id` (String.t): The id of the budget. \"last-used\" can be used to specify the last used budget and \"default\" can be used if default budget selection is enabled (see: https://api.ynab.com/#oauth-default-budget).
  - `scheduled_transaction_id` (String.t): The id of the scheduled transaction
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, YNAB.Model.ScheduledTransactionResponse.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec get_scheduled_transaction_by_id(Tesla.Env.client(), String.t(), String.t(), keyword()) ::
          {:ok, YNAB.Model.ScheduledTransactionResponse.t()}
          | {:ok, YNAB.Model.ErrorResponse.t()}
          | {:error, Tesla.Env.t()}
  def get_scheduled_transaction_by_id(
        connection,
        budget_id,
        scheduled_transaction_id,
        _opts \\ []
      ) do
    request =
      %{}
      |> method(:get)
      |> url("/budgets/#{budget_id}/scheduled_transactions/#{scheduled_transaction_id}")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, YNAB.Model.ScheduledTransactionResponse},
      {404, YNAB.Model.ErrorResponse},
      {:default, YNAB.Model.ErrorResponse}
    ])
  end

  @doc """
  List scheduled transactions
  Returns all scheduled transactions

  ### Parameters

  - `connection` (YNAB.Connection): Connection to server
  - `budget_id` (String.t): The id of the budget. \"last-used\" can be used to specify the last used budget and \"default\" can be used if default budget selection is enabled (see: https://api.ynab.com/#oauth-default-budget).
  - `opts` (keyword): Optional parameters
    - `:last_knowledge_of_server` (integer()): The starting server knowledge.  If provided, only entities that have changed since `last_knowledge_of_server` will be included.

  ### Returns

  - `{:ok, YNAB.Model.ScheduledTransactionsResponse.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec get_scheduled_transactions(Tesla.Env.client(), String.t(), keyword()) ::
          {:ok, YNAB.Model.ScheduledTransactionsResponse.t()}
          | {:ok, YNAB.Model.ErrorResponse.t()}
          | {:error, Tesla.Env.t()}
  def get_scheduled_transactions(connection, budget_id, opts \\ []) do
    optional_params = %{
      :last_knowledge_of_server => :query
    }

    request =
      %{}
      |> method(:get)
      |> url("/budgets/#{budget_id}/scheduled_transactions")
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, YNAB.Model.ScheduledTransactionsResponse},
      {404, YNAB.Model.ErrorResponse},
      {:default, YNAB.Model.ErrorResponse}
    ])
  end
end
