# NOTE: This file is auto generated by OpenAPI Generator 7.5.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule YNAB.Api.User do
  @moduledoc """
  API calls for all endpoints tagged `User`.
  """

  alias YNAB.Connection
  import YNAB.RequestBuilder

  @doc """
  User info
  Returns authenticated user information

  ### Parameters

  - `connection` (YNAB.Connection): Connection to server
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, YNAB.Model.UserResponse.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec get_user(Tesla.Env.client(), keyword()) ::
          {:ok, YNAB.Model.UserResponse.t()}
          | {:ok, YNAB.Model.ErrorResponse.t()}
          | {:error, Tesla.Env.t()}
  def get_user(connection, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/user")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, YNAB.Model.UserResponse},
      {:default, YNAB.Model.ErrorResponse}
    ])
  end
end
