# NOTE: This file is auto generated by OpenAPI Generator 7.5.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule YNAB.Model.AccountsResponseData do
  @moduledoc """

  """

  @derive Jason.Encoder
  defstruct [
    :accounts,
    :server_knowledge
  ]

  @type t :: %__MODULE__{
          :accounts => [YNAB.Model.Account.t()],
          :server_knowledge => integer()
        }

  alias YNAB.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:accounts, :list, YNAB.Model.Account)
  end
end
