# NOTE: This file is auto generated by OpenAPI Generator 7.5.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule YNAB.Model.Account do
  @moduledoc """

  """

  @derive Jason.Encoder
  defstruct [
    :id,
    :name,
    :type,
    :on_budget,
    :closed,
    :note,
    :balance,
    :cleared_balance,
    :uncleared_balance,
    :transfer_payee_id,
    :direct_import_linked,
    :direct_import_in_error,
    :last_reconciled_at,
    :debt_original_balance,
    :debt_interest_rates,
    :debt_minimum_payments,
    :debt_escrow_amounts,
    :deleted
  ]

  @type t :: %__MODULE__{
          :id => String.t(),
          :name => String.t(),
          :type => YNAB.Model.AccountType.t(),
          :on_budget => boolean(),
          :closed => boolean(),
          :note => String.t() | nil,
          :balance => integer(),
          :cleared_balance => integer(),
          :uncleared_balance => integer(),
          :transfer_payee_id => String.t() | nil,
          :direct_import_linked => boolean() | nil,
          :direct_import_in_error => boolean() | nil,
          :last_reconciled_at => DateTime.t() | nil,
          :debt_original_balance => integer() | nil,
          :debt_interest_rates => %{optional(String.t()) => integer()} | nil,
          :debt_minimum_payments => %{optional(String.t()) => integer()} | nil,
          :debt_escrow_amounts => %{optional(String.t()) => integer()} | nil,
          :deleted => boolean()
        }

  alias YNAB.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:type, :struct, YNAB.Model.AccountType)
    |> Deserializer.deserialize(:last_reconciled_at, :datetime, nil)
  end
end
