# NOTE: This file is auto generated by OpenAPI Generator 7.5.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule YNAB.Model.BudgetSummaryResponseData do
  @moduledoc """

  """

  @derive Jason.Encoder
  defstruct [
    :budgets,
    :default_budget
  ]

  @type t :: %__MODULE__{
          :budgets => [YNAB.Model.BudgetSummary.t()],
          :default_budget => YNAB.Model.BudgetSummary.t() | nil
        }

  alias YNAB.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:budgets, :list, YNAB.Model.BudgetSummary)
    |> Deserializer.deserialize(:default_budget, :struct, YNAB.Model.BudgetSummary)
  end
end
