# NOTE: This file is auto generated by OpenAPI Generator 7.5.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule YNAB.Model.BudgetSummary do
  @moduledoc """

  """

  @derive Jason.Encoder
  defstruct [
    :id,
    :name,
    :last_modified_on,
    :first_month,
    :last_month,
    :date_format,
    :currency_format,
    :accounts
  ]

  @type t :: %__MODULE__{
          :id => String.t(),
          :name => String.t(),
          :last_modified_on => DateTime.t() | nil,
          :first_month => Date.t() | nil,
          :last_month => Date.t() | nil,
          :date_format => YNAB.Model.DateFormat.t() | nil,
          :currency_format => YNAB.Model.CurrencyFormat.t() | nil,
          :accounts => [YNAB.Model.Account.t()] | nil
        }

  alias YNAB.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:last_modified_on, :datetime, nil)
    |> Deserializer.deserialize(:first_month, :date, nil)
    |> Deserializer.deserialize(:last_month, :date, nil)
    |> Deserializer.deserialize(:date_format, :struct, YNAB.Model.DateFormat)
    |> Deserializer.deserialize(:currency_format, :struct, YNAB.Model.CurrencyFormat)
    |> Deserializer.deserialize(:accounts, :list, YNAB.Model.Account)
  end
end
