# NOTE: This file is auto generated by OpenAPI Generator 7.5.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule YNAB.Model.BudgetSettings do
  @moduledoc """

  """

  @derive Jason.Encoder
  defstruct [
    :date_format,
    :currency_format
  ]

  @type t :: %__MODULE__{
          :date_format => YNAB.Model.DateFormat.t() | nil,
          :currency_format => YNAB.Model.CurrencyFormat.t() | nil
        }

  alias YNAB.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:date_format, :struct, YNAB.Model.DateFormat)
    |> Deserializer.deserialize(:currency_format, :struct, YNAB.Model.CurrencyFormat)
  end
end
