# NOTE: This file is auto generated by OpenAPI Generator 7.5.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule YNAB.Model.BudgetSettingsResponseData do
  @moduledoc """

  """

  @derive Jason.Encoder
  defstruct [
    :settings
  ]

  @type t :: %__MODULE__{
          :settings => YNAB.Model.BudgetSettings.t()
        }

  alias YNAB.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:settings, :struct, YNAB.Model.BudgetSettings)
  end
end
