# NOTE: This file is auto generated by OpenAPI Generator 7.5.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule YNAB.Model.BudgetDetail do
  @moduledoc """

  """

  @derive Jason.Encoder
  defstruct [
    :id,
    :name,
    :last_modified_on,
    :first_month,
    :last_month,
    :date_format,
    :currency_format,
    :accounts,
    :payees,
    :payee_locations,
    :category_groups,
    :categories,
    :months,
    :transactions,
    :subtransactions,
    :scheduled_transactions,
    :scheduled_subtransactions
  ]

  @type t :: %__MODULE__{
          :id => String.t(),
          :name => String.t(),
          :last_modified_on => DateTime.t() | nil,
          :first_month => Date.t() | nil,
          :last_month => Date.t() | nil,
          :date_format => YNAB.Model.DateFormat.t() | nil,
          :currency_format => YNAB.Model.CurrencyFormat.t() | nil,
          :accounts => [YNAB.Model.Account.t()] | nil,
          :payees => [YNAB.Model.Payee.t()] | nil,
          :payee_locations => [YNAB.Model.PayeeLocation.t()] | nil,
          :category_groups => [YNAB.Model.CategoryGroup.t()] | nil,
          :categories => [YNAB.Model.Category.t()] | nil,
          :months => [YNAB.Model.MonthDetail.t()] | nil,
          :transactions => [YNAB.Model.TransactionSummary.t()] | nil,
          :subtransactions => [YNAB.Model.SubTransaction.t()] | nil,
          :scheduled_transactions => [YNAB.Model.ScheduledTransactionSummary.t()] | nil,
          :scheduled_subtransactions => [YNAB.Model.ScheduledSubTransaction.t()] | nil
        }

  alias YNAB.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:last_modified_on, :datetime, nil)
    |> Deserializer.deserialize(:first_month, :date, nil)
    |> Deserializer.deserialize(:last_month, :date, nil)
    |> Deserializer.deserialize(:date_format, :struct, YNAB.Model.DateFormat)
    |> Deserializer.deserialize(:currency_format, :struct, YNAB.Model.CurrencyFormat)
    |> Deserializer.deserialize(:accounts, :list, YNAB.Model.Account)
    |> Deserializer.deserialize(:payees, :list, YNAB.Model.Payee)
    |> Deserializer.deserialize(:payee_locations, :list, YNAB.Model.PayeeLocation)
    |> Deserializer.deserialize(:category_groups, :list, YNAB.Model.CategoryGroup)
    |> Deserializer.deserialize(:categories, :list, YNAB.Model.Category)
    |> Deserializer.deserialize(:months, :list, YNAB.Model.MonthDetail)
    |> Deserializer.deserialize(:transactions, :list, YNAB.Model.TransactionSummary)
    |> Deserializer.deserialize(:subtransactions, :list, YNAB.Model.SubTransaction)
    |> Deserializer.deserialize(
      :scheduled_transactions,
      :list,
      YNAB.Model.ScheduledTransactionSummary
    )
    |> Deserializer.deserialize(
      :scheduled_subtransactions,
      :list,
      YNAB.Model.ScheduledSubTransaction
    )
  end
end
