# NOTE: This file is auto generated by OpenAPI Generator 7.5.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule YNAB.Model.BulkResponseData do
  @moduledoc """

  """

  @derive Jason.Encoder
  defstruct [
    :bulk
  ]

  @type t :: %__MODULE__{
          :bulk => YNAB.Model.BulkResponseDataBulk.t()
        }

  alias YNAB.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:bulk, :struct, YNAB.Model.BulkResponseDataBulk)
  end
end
