# NOTE: This file is auto generated by OpenAPI Generator 7.5.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule YNAB.Model.BulkResponseDataBulk do
  @moduledoc """

  """

  @derive Jason.Encoder
  defstruct [
    :transaction_ids,
    :duplicate_import_ids
  ]

  @type t :: %__MODULE__{
          :transaction_ids => [String.t()],
          :duplicate_import_ids => [String.t()]
        }

  def decode(value) do
    value
  end
end
