# NOTE: This file is auto generated by OpenAPI Generator 7.5.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule YNAB.Model.CategoryGroupWithCategories do
  @moduledoc """

  """

  @derive Jason.Encoder
  defstruct [
    :id,
    :name,
    :hidden,
    :deleted,
    :categories
  ]

  @type t :: %__MODULE__{
          :id => String.t(),
          :name => String.t(),
          :hidden => boolean(),
          :deleted => boolean(),
          :categories => [YNAB.Model.Category.t()]
        }

  alias YNAB.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:categories, :list, YNAB.Model.Category)
  end
end
