# NOTE: This file is auto generated by OpenAPI Generator 7.5.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule YNAB.Model.CategoriesResponseData do
  @moduledoc """

  """

  @derive Jason.Encoder
  defstruct [
    :category_groups,
    :server_knowledge
  ]

  @type t :: %__MODULE__{
          :category_groups => [YNAB.Model.CategoryGroupWithCategories.t()],
          :server_knowledge => integer()
        }

  alias YNAB.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:category_groups, :list, YNAB.Model.CategoryGroupWithCategories)
  end
end
