# NOTE: This file is auto generated by OpenAPI Generator 7.5.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule YNAB.Model.Category do
  @moduledoc """

  """

  @derive Jason.Encoder
  defstruct [
    :id,
    :category_group_id,
    :category_group_name,
    :name,
    :hidden,
    :original_category_group_id,
    :note,
    :budgeted,
    :activity,
    :balance,
    :goal_type,
    :goal_day,
    :goal_cadence,
    :goal_cadence_frequency,
    :goal_creation_month,
    :goal_target,
    :goal_target_month,
    :goal_percentage_complete,
    :goal_months_to_budget,
    :goal_under_funded,
    :goal_overall_funded,
    :goal_overall_left,
    :deleted
  ]

  @type t :: %__MODULE__{
          :id => String.t(),
          :category_group_id => String.t(),
          :category_group_name => String.t() | nil,
          :name => String.t(),
          :hidden => boolean(),
          :original_category_group_id => String.t() | nil,
          :note => String.t() | nil,
          :budgeted => integer(),
          :activity => integer(),
          :balance => integer(),
          :goal_type => String.t() | nil,
          :goal_day => integer() | nil,
          :goal_cadence => integer() | nil,
          :goal_cadence_frequency => integer() | nil,
          :goal_creation_month => Date.t() | nil,
          :goal_target => integer() | nil,
          :goal_target_month => Date.t() | nil,
          :goal_percentage_complete => integer() | nil,
          :goal_months_to_budget => integer() | nil,
          :goal_under_funded => integer() | nil,
          :goal_overall_funded => integer() | nil,
          :goal_overall_left => integer() | nil,
          :deleted => boolean()
        }

  alias YNAB.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:goal_creation_month, :date, nil)
    |> Deserializer.deserialize(:goal_target_month, :date, nil)
  end
end
