# NOTE: This file is auto generated by OpenAPI Generator 7.5.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule YNAB.Model.CategoryGroup do
  @moduledoc """

  """

  @derive Jason.Encoder
  defstruct [
    :id,
    :name,
    :hidden,
    :deleted
  ]

  @type t :: %__MODULE__{
          :id => String.t(),
          :name => String.t(),
          :hidden => boolean(),
          :deleted => boolean()
        }

  def decode(value) do
    value
  end
end
