# NOTE: This file is auto generated by OpenAPI Generator 7.5.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule YNAB.Model.CurrencyFormat do
  @moduledoc """
  The currency format setting for the budget.  In some cases the format will not be available and will be specified as null.
  """

  @derive Jason.Encoder
  defstruct [
    :iso_code,
    :example_format,
    :decimal_digits,
    :decimal_separator,
    :symbol_first,
    :group_separator,
    :currency_symbol,
    :display_symbol
  ]

  @type t :: %__MODULE__{
          :iso_code => String.t(),
          :example_format => String.t(),
          :decimal_digits => integer(),
          :decimal_separator => String.t(),
          :symbol_first => boolean(),
          :group_separator => String.t(),
          :currency_symbol => String.t(),
          :display_symbol => boolean()
        }

  def decode(value) do
    value
  end
end
