# NOTE: This file is auto generated by OpenAPI Generator 7.5.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule YNAB.Model.DateFormat do
  @moduledoc """
  The date format setting for the budget.  In some cases the format will not be available and will be specified as null.
  """

  @derive Jason.Encoder
  defstruct [
    :format
  ]

  @type t :: %__MODULE__{
          :format => String.t()
        }

  def decode(value) do
    value
  end
end
