# NOTE: This file is auto generated by OpenAPI Generator 7.5.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule YNAB.Model.ErrorDetail do
  @moduledoc """

  """

  @derive Jason.Encoder
  defstruct [
    :id,
    :name,
    :detail
  ]

  @type t :: %__MODULE__{
          :id => String.t(),
          :name => String.t(),
          :detail => String.t()
        }

  def decode(value) do
    value
  end
end
