# NOTE: This file is auto generated by OpenAPI Generator 7.5.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule YNAB.Model.MonthSummariesResponseData do
  @moduledoc """

  """

  @derive Jason.Encoder
  defstruct [
    :months,
    :server_knowledge
  ]

  @type t :: %__MODULE__{
          :months => [YNAB.Model.MonthSummary.t()],
          :server_knowledge => integer()
        }

  alias YNAB.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:months, :list, YNAB.Model.MonthSummary)
  end
end
