# NOTE: This file is auto generated by OpenAPI Generator 7.5.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule YNAB.Model.PatchTransactionsWrapper do
  @moduledoc """

  """

  @derive Jason.Encoder
  defstruct [
    :transactions
  ]

  @type t :: %__MODULE__{
          :transactions => [YNAB.Model.SaveTransactionWithIdOrImportId.t()]
        }

  alias YNAB.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:transactions, :list, YNAB.Model.SaveTransactionWithIdOrImportId)
  end
end
