# NOTE: This file is auto generated by OpenAPI Generator 7.5.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule YNAB.Model.PayeeLocationsResponseData do
  @moduledoc """

  """

  @derive Jason.Encoder
  defstruct [
    :payee_locations
  ]

  @type t :: %__MODULE__{
          :payee_locations => [YNAB.Model.PayeeLocation.t()]
        }

  alias YNAB.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:payee_locations, :list, YNAB.Model.PayeeLocation)
  end
end
