# NOTE: This file is auto generated by OpenAPI Generator 7.5.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule YNAB.Model.PayeesResponseData do
  @moduledoc """

  """

  @derive Jason.Encoder
  defstruct [
    :payees,
    :server_knowledge
  ]

  @type t :: %__MODULE__{
          :payees => [YNAB.Model.Payee.t()],
          :server_knowledge => integer()
        }

  alias YNAB.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:payees, :list, YNAB.Model.Payee)
  end
end
