# NOTE: This file is auto generated by OpenAPI Generator 7.5.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule YNAB.Model.PostAccountWrapper do
  @moduledoc """

  """

  @derive Jason.Encoder
  defstruct [
    :account
  ]

  @type t :: %__MODULE__{
          :account => YNAB.Model.SaveAccount.t()
        }

  alias YNAB.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:account, :struct, YNAB.Model.SaveAccount)
  end
end
