# NOTE: This file is auto generated by OpenAPI Generator 7.5.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule YNAB.Model.PostTransactionsWrapper do
  @moduledoc """

  """

  @derive Jason.Encoder
  defstruct [
    :transaction,
    :transactions
  ]

  @type t :: %__MODULE__{
          :transaction => YNAB.Model.NewTransaction.t() | nil,
          :transactions => [YNAB.Model.NewTransaction.t()] | nil
        }

  alias YNAB.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:transaction, :struct, YNAB.Model.NewTransaction)
    |> Deserializer.deserialize(:transactions, :list, YNAB.Model.NewTransaction)
  end
end
