# NOTE: This file is auto generated by OpenAPI Generator 7.5.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule YNAB.Model.PutTransactionWrapper do
  @moduledoc """

  """

  @derive Jason.Encoder
  defstruct [
    :transaction
  ]

  @type t :: %__MODULE__{
          :transaction => YNAB.Model.ExistingTransaction.t()
        }

  alias YNAB.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:transaction, :struct, YNAB.Model.ExistingTransaction)
  end
end
