# NOTE: This file is auto generated by OpenAPI Generator 7.5.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule YNAB.Model.SaveCategory do
  @moduledoc """

  """

  @derive Jason.Encoder
  defstruct [
    :name,
    :note,
    :category_group_id
  ]

  @type t :: %__MODULE__{
          :name => String.t() | nil,
          :note => String.t() | nil,
          :category_group_id => String.t() | nil
        }

  def decode(value) do
    value
  end
end
