# NOTE: This file is auto generated by OpenAPI Generator 7.5.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule YNAB.Model.SaveTransactionsResponseData do
  @moduledoc """

  """

  @derive Jason.Encoder
  defstruct [
    :transaction_ids,
    :transaction,
    :transactions,
    :duplicate_import_ids,
    :server_knowledge
  ]

  @type t :: %__MODULE__{
          :transaction_ids => [String.t()],
          :transaction => YNAB.Model.TransactionDetail.t() | nil,
          :transactions => [YNAB.Model.TransactionDetail.t()] | nil,
          :duplicate_import_ids => [String.t()] | nil,
          :server_knowledge => integer()
        }

  alias YNAB.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:transaction, :struct, YNAB.Model.TransactionDetail)
    |> Deserializer.deserialize(:transactions, :list, YNAB.Model.TransactionDetail)
  end
end
