# NOTE: This file is auto generated by OpenAPI Generator 7.5.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule YNAB.Model.SaveAccount do
  @moduledoc """

  """

  @derive Jason.Encoder
  defstruct [
    :name,
    :type,
    :balance
  ]

  @type t :: %__MODULE__{
          :name => String.t(),
          :type => YNAB.Model.AccountType.t(),
          :balance => integer()
        }

  alias YNAB.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:type, :struct, YNAB.Model.AccountType)
  end
end
