# NOTE: This file is auto generated by OpenAPI Generator 7.5.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule YNAB.Model.SaveSubTransaction do
  @moduledoc """

  """

  @derive Jason.Encoder
  defstruct [
    :amount,
    :payee_id,
    :payee_name,
    :category_id,
    :memo
  ]

  @type t :: %__MODULE__{
          :amount => integer(),
          :payee_id => String.t() | nil,
          :payee_name => String.t() | nil,
          :category_id => String.t() | nil,
          :memo => String.t() | nil
        }

  def decode(value) do
    value
  end
end
