# NOTE: This file is auto generated by OpenAPI Generator 7.5.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule YNAB.Model.ScheduledTransactionsResponseData do
  @moduledoc """

  """

  @derive Jason.Encoder
  defstruct [
    :scheduled_transactions,
    :server_knowledge
  ]

  @type t :: %__MODULE__{
          :scheduled_transactions => [YNAB.Model.ScheduledTransactionDetail.t()],
          :server_knowledge => integer()
        }

  alias YNAB.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(
      :scheduled_transactions,
      :list,
      YNAB.Model.ScheduledTransactionDetail
    )
  end
end
