# NOTE: This file is auto generated by OpenAPI Generator 7.5.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule YNAB.Model.ScheduledSubTransaction do
  @moduledoc """

  """

  @derive Jason.Encoder
  defstruct [
    :id,
    :scheduled_transaction_id,
    :amount,
    :memo,
    :payee_id,
    :category_id,
    :transfer_account_id,
    :deleted
  ]

  @type t :: %__MODULE__{
          :id => String.t(),
          :scheduled_transaction_id => String.t(),
          :amount => integer(),
          :memo => String.t() | nil,
          :payee_id => String.t() | nil,
          :category_id => String.t() | nil,
          :transfer_account_id => String.t() | nil,
          :deleted => boolean()
        }

  def decode(value) do
    value
  end
end
