# NOTE: This file is auto generated by OpenAPI Generator 7.5.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule YNAB.Model.TransactionsResponseData do
  @moduledoc """

  """

  @derive Jason.Encoder
  defstruct [
    :transactions,
    :server_knowledge
  ]

  @type t :: %__MODULE__{
          :transactions => [YNAB.Model.TransactionDetail.t()],
          :server_knowledge => integer()
        }

  alias YNAB.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:transactions, :list, YNAB.Model.TransactionDetail)
  end
end
