# NOTE: This file is auto generated by OpenAPI Generator 7.5.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule YNAB.Model.TransactionSummary do
  @moduledoc """

  """

  @derive Jason.Encoder
  defstruct [
    :id,
    :date,
    :amount,
    :memo,
    :cleared,
    :approved,
    :flag_color,
    :flag_name,
    :account_id,
    :payee_id,
    :category_id,
    :transfer_account_id,
    :transfer_transaction_id,
    :matched_transaction_id,
    :import_id,
    :import_payee_name,
    :import_payee_name_original,
    :debt_transaction_type,
    :deleted
  ]

  @type t :: %__MODULE__{
          :id => String.t(),
          :date => Date.t(),
          :amount => integer(),
          :memo => String.t() | nil,
          :cleared => YNAB.Model.TransactionClearedStatus.t(),
          :approved => boolean(),
          :flag_color => YNAB.Model.TransactionFlagColor.t() | nil,
          :flag_name => String.t() | nil,
          :account_id => String.t(),
          :payee_id => String.t() | nil,
          :category_id => String.t() | nil,
          :transfer_account_id => String.t() | nil,
          :transfer_transaction_id => String.t() | nil,
          :matched_transaction_id => String.t() | nil,
          :import_id => String.t() | nil,
          :import_payee_name => String.t() | nil,
          :import_payee_name_original => String.t() | nil,
          :debt_transaction_type => String.t() | nil,
          :deleted => boolean()
        }

  alias YNAB.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:date, :date, nil)
    |> Deserializer.deserialize(:cleared, :struct, YNAB.Model.TransactionClearedStatus)
    |> Deserializer.deserialize(:flag_color, :struct, YNAB.Model.TransactionFlagColor)
  end
end
