# NOTE: This file is auto generated by OpenAPI Generator 7.5.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule YNAB.Model.User do
  @moduledoc """

  """

  @derive Jason.Encoder
  defstruct [
    :id
  ]

  @type t :: %__MODULE__{
          :id => String.t()
        }

  def decode(value) do
    value
  end
end
