# NOTE: This file is auto generated by OpenAPI Generator 7.5.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule YNAB.Model.UserResponseData do
  @moduledoc """

  """

  @derive Jason.Encoder
  defstruct [
    :user
  ]

  @type t :: %__MODULE__{
          :user => YNAB.Model.User.t()
        }

  alias YNAB.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:user, :struct, YNAB.Model.User)
  end
end
